### ISSUE TITLE
its not working when I install

### ISSUE THREAD

**Issue by ComradeStonedSoviet** [DADi590/F1DP#5]
I have Team X update, and it still keeps tellin me that Im missing the perameter regarding the 1.2 US version Dos Release, its stressing me out, pls help
![image](https://user-images.githubusercontent.com/113244566/189513766-9bc82530-f5f3-4b51-919d-539469a4b321.png)

**Comment by DADi590** [comment]
Hi. Did you pass the file as parameter to that installer? You need to either call the installer on the command line with the Fallout file as parameter, or you can just drag the Fallout file to the installer file, as I say there.
